# Generated by Django 3.0 on 2020-03-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecontent',
            name='content',
            field=models.CharField(max_length=4096, verbose_name='内容'),
        ),
    ]
